-- =====================================================
-- V11: 人工成本表结构（PostgreSQL）
-- =====================================================

CREATE TABLE IF NOT EXISTS labor_cost (
    -- 主键
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 关联合同 ID（应用层校验存在性）
    contract_id  BIGINT         NOT NULL,
    -- 人员姓名
    person_name  VARCHAR(50)    NOT NULL,
    -- 成本月份，格式 YYYY-MM
    cost_month   VARCHAR(7)     NOT NULL,
    -- 成本金额（元）
    amount       NUMERIC(14, 2) NOT NULL,
    -- 备注
    remark       VARCHAR(500),
    create_by    VARCHAR(50),
    create_time  TIMESTAMP,
    update_by    VARCHAR(50),
    update_time  TIMESTAMP,
    CONSTRAINT uk_labor_contract_person_month UNIQUE (contract_id, person_name, cost_month)
);

CREATE INDEX IF NOT EXISTS idx_labor_contract_id ON labor_cost (contract_id);
