-- =====================================================
-- V13: 项目维度架构调整
-- 1) 新建 project 表  2) 清空业务测试数据  3) 关联关系从合同改为项目
-- =====================================================

-- 1. 项目表（顶层业务实体）
CREATE TABLE IF NOT EXISTS project (
    -- 主键
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 项目编号，规则 PRJ+yyyyMMdd+4位流水，全局唯一
    project_no   VARCHAR(30)  NOT NULL,
    -- 项目名称
    name         VARCHAR(200) NOT NULL,
    -- 项目类型：审计/税务/咨询/其他
    type         VARCHAR(30)  NOT NULL,
    -- 客户名称
    client_name  VARCHAR(200) NOT NULL,
    -- 项目负责人
    owner_name   VARCHAR(50)  NOT NULL,
    -- 项目期间起
    start_date   DATE         NOT NULL,
    -- 项目期间止
    end_date     DATE         NOT NULL,
    -- 状态：0-进行中 1-已完成 2-已归档
    status       SMALLINT     NOT NULL DEFAULT 0,
    -- 备注
    remark       VARCHAR(500),
    create_by    VARCHAR(50),
    create_time  TIMESTAMP,
    update_by    VARCHAR(50),
    update_time  TIMESTAMP,
    CONSTRAINT uk_project_no UNIQUE (project_no)
);

CREATE INDEX IF NOT EXISTS idx_project_client_name ON project (client_name);
CREATE INDEX IF NOT EXISTS idx_project_status ON project (status);

-- 2. 清空业务测试数据（用户确认清库重来；权限体系数据保留）
TRUNCATE TABLE contract_payment, reimbursement, labor_cost, confirmation, contract RESTART IDENTITY;

-- 3. 合同挂项目（必填）
ALTER TABLE contract ADD COLUMN project_id BIGINT NOT NULL;
CREATE INDEX IF NOT EXISTS idx_contract_project_id ON contract (project_id);

-- 4. 报销/人工成本/函证的关联从合同改为项目
ALTER TABLE reimbursement RENAME COLUMN contract_id TO project_id;
ALTER TABLE labor_cost RENAME COLUMN contract_id TO project_id;
ALTER TABLE labor_cost ALTER COLUMN project_id SET NOT NULL;
ALTER TABLE confirmation RENAME COLUMN contract_id TO project_id;
