-- =====================================================
-- V16: 邮箱登录 + 合同附件
-- =====================================================

-- 用户邮箱唯一（PG 唯一索引允许多个 NULL，存量无邮箱用户不受影响）
ALTER TABLE sys_user ADD CONSTRAINT uk_sys_user_email UNIQUE (email);

-- 管理员种子邮箱（用于邮箱登录验证）
UPDATE sys_user SET email = 'admin@firm.cn' WHERE username = 'admin' AND (email IS NULL OR email = '');

-- 合同附件表
CREATE TABLE IF NOT EXISTS contract_attachment (
    -- 主键
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 关联合同 ID
    contract_id  BIGINT       NOT NULL,
    -- 原始文件名
    file_name    VARCHAR(255) NOT NULL,
    -- 存储文件名（UUID 扩展名）
    stored_name  VARCHAR(100) NOT NULL,
    -- 文件大小（字节）
    file_size    BIGINT       NOT NULL,
    -- 内容类型
    content_type VARCHAR(100),
    create_by    VARCHAR(50),
    create_time  TIMESTAMP,
    update_by    VARCHAR(50),
    update_time  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_attachment_contract_id ON contract_attachment (contract_id);
