-- =====================================================
-- V17: 报销模块增强——明细行模型 + 财务环节
-- =====================================================

-- 清空报销测试数据（用户确认）
TRUNCATE TABLE reimbursement RESTART IDENTITY;

-- 头表结构调整：金额/类别/日期下沉到明细行，新增财务标记与一级审批人
ALTER TABLE reimbursement DROP COLUMN category;
ALTER TABLE reimbursement DROP COLUMN expense_date;
ALTER TABLE reimbursement DROP COLUMN amount;
ALTER TABLE reimbursement ADD COLUMN total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;
ALTER TABLE reimbursement ADD COLUMN is_invoice_received BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reimbursement ADD COLUMN is_paid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reimbursement ADD COLUMN primary_approver_name VARCHAR(50);

-- 状态语义变更（数据已清空）：0-草稿 1-待审批 2-已批准 3-已驳回 4-待终审
COMMENT ON COLUMN reimbursement.status IS '状态：0-草稿 1-待审批 2-已批准 3-已驳回 4-待终审';

-- 费用明细表
CREATE TABLE IF NOT EXISTS reimbursement_item (
    -- 主键
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 所属报销单 ID
    reimbursement_id BIGINT         NOT NULL,
    -- 费用类别：差旅费/交通费/办公费/餐饮费/其他
    category         VARCHAR(30)    NOT NULL,
    -- 金额（元）
    amount           NUMERIC(14, 2) NOT NULL,
    -- 费用日期
    expense_date     DATE           NOT NULL,
    -- 事由说明
    description      VARCHAR(300),
    -- 发票号（可选）
    invoice_number   VARCHAR(50),
    -- 是否增值税发票
    is_vat_invoice   BOOLEAN        NOT NULL DEFAULT FALSE,
    create_time      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reimbursement_item_rid ON reimbursement_item (reimbursement_id);

-- 报销附件表（发票扫描件等）
CREATE TABLE IF NOT EXISTS reimbursement_attachment (
    -- 主键
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 所属报销单 ID
    reimbursement_id BIGINT       NOT NULL,
    -- 原始文件名
    file_name        VARCHAR(255) NOT NULL,
    -- 存储对象路径（Supabase Storage）
    stored_name      VARCHAR(200) NOT NULL,
    -- 文件大小（字节）
    file_size        BIGINT       NOT NULL,
    -- 内容类型
    content_type     VARCHAR(100),
    create_by        VARCHAR(50),
    create_time      TIMESTAMP,
    update_by        VARCHAR(50),
    update_time      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reimbursement_attachment_rid ON reimbursement_attachment (reimbursement_id);

-- 财务操作按钮权限点（挂在报销管理菜单 120 下）
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(125, 120, '财务操作', NULL, NULL, 'business:reimbursement:finance', NULL, 2, 5, NOW());

-- 角色授权：系统管理员与项目经理具备财务操作权限
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 125), (2, 125);

-- 推进菜单表自增序列到当前最大值
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), (SELECT MAX(id) FROM sys_menu));
