-- =====================================================
-- V19: 函证模块增强——实务字段 + 扫描件附件
-- =====================================================

-- 函证新增实务字段
ALTER TABLE confirmation ADD COLUMN send_tracking_no VARCHAR(100);
ALTER TABLE confirmation ADD COLUMN confirmation_method VARCHAR(30);
ALTER TABLE confirmation ADD COLUMN reply_tracking_no VARCHAR(100);
ALTER TABLE confirmation ADD COLUMN has_reply BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE confirmation ADD COLUMN reply_matched BOOLEAN;
ALTER TABLE confirmation ADD COLUMN discrepancy_reason VARCHAR(500);

-- 函证附件表（原始函证/回函扫描件，attachment_type 区分）
CREATE TABLE IF NOT EXISTS confirmation_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_id BIGINT       NOT NULL,
    -- original=原始函证扫描件 reply=回函扫描件
    attachment_type VARCHAR(20)  NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    stored_name     VARCHAR(200) NOT NULL,
    file_size       BIGINT       NOT NULL,
    content_type    VARCHAR(100),
    create_by       VARCHAR(50),
    create_time     TIMESTAMP,
    update_by       VARCHAR(50),
    update_time     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_confirmation_attachment_cid ON confirmation_attachment (confirmation_id);
