-- =====================================================
-- V1: 系统基础表结构初始化（PostgreSQL / Supabase）
-- RBAC 五表模型：用户、角色、菜单（含按钮权限点）、用户角色、角色菜单
-- =====================================================

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    -- 用户ID
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 登录账号
    username    VARCHAR(50)  NOT NULL,
    -- 密码（BCrypt 加密）
    password    VARCHAR(100) NOT NULL,
    -- 姓名/昵称
    nickname    VARCHAR(50),
    -- 邮箱
    email       VARCHAR(100),
    -- 手机号
    phone       VARCHAR(20),
    -- 状态：1-启用 0-禁用
    status      SMALLINT     NOT NULL DEFAULT 1,
    -- 创建人
    create_by   VARCHAR(50),
    -- 创建时间
    create_time TIMESTAMP,
    -- 更新人
    update_by   VARCHAR(50),
    -- 更新时间
    update_time TIMESTAMP,
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

-- 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    -- 角色ID
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 角色编码，如 admin / manager / employee
    role_code   VARCHAR(50)  NOT NULL,
    -- 角色名称
    role_name   VARCHAR(50)  NOT NULL,
    -- 角色描述
    description VARCHAR(200),
    -- 状态：1-启用 0-禁用
    status      SMALLINT     NOT NULL DEFAULT 1,
    create_by   VARCHAR(50),
    create_time TIMESTAMP,
    update_by   VARCHAR(50),
    update_time TIMESTAMP,
    CONSTRAINT uk_sys_role_code UNIQUE (role_code)
);

-- 菜单表（目录/菜单/按钮权限点一体建模）
CREATE TABLE IF NOT EXISTS sys_menu (
    -- 菜单ID
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 父菜单ID，0 表示根节点
    parent_id   BIGINT       NOT NULL DEFAULT 0,
    -- 菜单/按钮名称
    name        VARCHAR(50)  NOT NULL,
    -- 路由路径（目录/菜单）
    path        VARCHAR(200),
    -- 前端组件路径（菜单）
    component   VARCHAR(200),
    -- 权限标识（如 system:user:list）
    perm        VARCHAR(100),
    -- 图标
    icon        VARCHAR(100),
    -- 类型：0-目录 1-菜单 2-按钮
    type        SMALLINT     NOT NULL DEFAULT 1,
    -- 排序号，越小越靠前
    sort        INT          NOT NULL DEFAULT 0,
    -- 是否可见：1-是 0-隐藏
    visible     SMALLINT     NOT NULL DEFAULT 1,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sys_menu_parent_id ON sys_menu (parent_id);

-- 用户角色关联表
CREATE TABLE IF NOT EXISTS sys_user_role (
    -- 主键
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 用户ID
    user_id BIGINT NOT NULL,
    -- 角色ID
    role_id BIGINT NOT NULL,
    CONSTRAINT uk_sys_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_sys_user_role_role_id ON sys_user_role (role_id);

-- 角色菜单关联表
CREATE TABLE IF NOT EXISTS sys_role_menu (
    -- 主键
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 角色ID
    role_id BIGINT NOT NULL,
    -- 菜单ID
    menu_id BIGINT NOT NULL,
    CONSTRAINT uk_sys_role_menu UNIQUE (role_id, menu_id)
);

CREATE INDEX IF NOT EXISTS idx_sys_role_menu_menu_id ON sys_role_menu (menu_id);
