-- =====================================================
-- V20: 项目参与人员表
-- =====================================================

CREATE TABLE IF NOT EXISTS project_member (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    -- 参与人员姓名（从系统用户下拉选择）
    member_name VARCHAR(50)  NOT NULL,
    -- 角色：合伙人/项目经理/现场负责人/组员
    member_role VARCHAR(30)  NOT NULL,
    sort        INT          NOT NULL DEFAULT 0,
    create_time TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_member_pid ON project_member (project_id);
