-- =====================================================
-- V22: 合伙人角色 + 部门管理
-- =====================================================

-- 合伙人角色（全部权限）
INSERT INTO sys_role (id, role_code, role_name, description, status, create_by, create_time)
VALUES (4, 'partner', '合伙人', '拥有系统全部权限', 1, 'system', NOW());

-- 合伙人授权全部菜单与按钮
INSERT INTO sys_role_menu (role_id, menu_id) SELECT 4, id FROM sys_menu;

-- 部门表
CREATE TABLE IF NOT EXISTS sys_department (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name   VARCHAR(100) NOT NULL,
    sort        INT          NOT NULL DEFAULT 0,
    create_by   VARCHAR(50),
    create_time TIMESTAMP,
    update_by   VARCHAR(50),
    update_time TIMESTAMP,
    CONSTRAINT uk_sys_department_name UNIQUE (dept_name)
);

-- 用户表加部门字段
ALTER TABLE sys_user ADD COLUMN dept_id BIGINT;

-- 部门管理菜单（ID 25 段，挂在系统管理目录下）
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(25, 1, '部门管理', '/system/dept', 'system/dept/index', 'system:dept:list', 'OfficeBuilding', 1, 4, NOW());

-- 部门管理按钮权限点
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(26, 25, '部门新增', NULL, NULL, 'system:dept:add', NULL, 2, 1, NOW()),
(27, 25, '部门编辑', NULL, NULL, 'system:dept:edit', NULL, 2, 2, NOW()),
(28, 25, '部门删除', NULL, NULL, 'system:dept:delete', NULL, 2, 3, NOW());

-- 授权：admin 全量
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 25), (1, 26), (1, 27), (1, 28);
-- 授权：partner 全量
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 25), (4, 26), (4, 27), (4, 28);

-- 推进菜单表自增序列
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), (SELECT MAX(id) FROM sys_menu));
