-- =====================================================
-- V23: 客户管理表
-- =====================================================

CREATE TABLE IF NOT EXISTS client (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_no            VARCHAR(30)   NOT NULL,
    client_name          VARCHAR(200)  NOT NULL,
    -- domestic=境内 overseas=境外
    client_type          VARCHAR(20)   NOT NULL DEFAULT 'domestic',
    dept_id              BIGINT        NOT NULL,
    -- 工商信息（境内客户）
    credit_code          VARCHAR(50),
    registered_capital   VARCHAR(100),
    registered_address   VARCHAR(500),
    legal_representative VARCHAR(100),
    business_scope       TEXT,
    -- 联系信息
    contact_person       VARCHAR(100),
    contact_phone        VARCHAR(50),
    remark               VARCHAR(500),
    create_by            VARCHAR(50),
    create_time          TIMESTAMP,
    update_by            VARCHAR(50),
    update_time          TIMESTAMP,
    CONSTRAINT uk_client_no UNIQUE (client_no)
);

CREATE INDEX IF NOT EXISTS idx_client_dept_id ON client (dept_id);
CREATE INDEX IF NOT EXISTS idx_client_name ON client (client_name);
