-- =====================================================
-- V26: 日程管理表
-- =====================================================

CREATE TABLE IF NOT EXISTS schedule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT,
    -- 所属用户 ID
    user_id      BIGINT       NOT NULL,
    -- 日程标题
    title        VARCHAR(200) NOT NULL,
    description  TEXT,
    -- 日期
    schedule_date DATE        NOT NULL,
    -- 工时（小时）
    hours        DECIMAL(4,1) NOT NULL DEFAULT 0,
    -- work=工作 leave=休假 travel=出差 other=其他
    type         VARCHAR(20)  NOT NULL DEFAULT 'work',
    create_by    VARCHAR(50),
    create_time  TIMESTAMP,
    update_by    VARCHAR(50),
    update_time  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_schedule_user_id ON schedule (user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_date ON schedule (schedule_date);
CREATE INDEX IF NOT EXISTS idx_schedule_project_id ON schedule (project_id);
