-- V33: 合同字号类型字典（合同字号按类型自动编号）
CREATE TABLE IF NOT EXISTS contract_no_type (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 字号简称：审/验/咨/代
    type_char     VARCHAR(10)  NOT NULL,
    -- 编号前缀：如 迈伊兹审约、迈伊兹审验、咨、代
    prefix        VARCHAR(50)  NOT NULL,
    -- 对应的合同类型（合同登记时按类型匹配取前缀）
    contract_type VARCHAR(50)  NOT NULL,
    remark        VARCHAR(200),
    create_by     VARCHAR(50),
    create_time   TIMESTAMP,
    update_by     VARCHAR(50),
    update_time   TIMESTAMP,
    CONSTRAINT uk_contract_no_type_char UNIQUE (type_char)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_contract_no_type_ctype ON contract_no_type (contract_type);

INSERT INTO contract_no_type (type_char, prefix, contract_type, remark, create_time, update_time) VALUES
('审', '迈伊兹审约', '审计',     '审计业务合同，如 迈伊兹审约(2026)第0001号', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('验', '迈伊兹审验', '验资',     '验资业务合同，如 迈伊兹审验(2026)第0001号', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('咨', '咨',       '税务咨询', '税务咨询类合同，如 咨(2026)第0001号',       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('代', '代',       '代理记账', '代理记账类合同，如 代(2026)第0001号',       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
