-- V36: 发票管理（合同 → 发票 → 收款核销）

-- 发票表
CREATE TABLE IF NOT EXISTS invoice (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no    VARCHAR(50)   NOT NULL,
    -- 挂靠合同（业务流：签合同后开发票）
    contract_id   BIGINT        NOT NULL,
    -- 客户 ID（冗余自合同所属项目，便于查询与留存）
    client_id     BIGINT        NOT NULL DEFAULT 0,
    -- 增值税专用发票 / 增值税普通发票
    type          VARCHAR(30)   NOT NULL,
    -- 价税合计（元）
    amount        NUMERIC(18,2) NOT NULL,
    -- 税率（%，可空）
    tax_rate      NUMERIC(5,2),
    -- 开票日期（开票动作时必填）
    invoice_date  DATE,
    -- 0-待开票 1-已开票 2-已作废
    status        SMALLINT      NOT NULL DEFAULT 0,
    remark        VARCHAR(500),
    create_by     VARCHAR(50),
    create_time   TIMESTAMP,
    update_by     VARCHAR(50),
    update_time   TIMESTAMP,
    CONSTRAINT uk_invoice_no UNIQUE (invoice_no)
);

CREATE INDEX IF NOT EXISTS idx_invoice_contract ON invoice (contract_id);
CREATE INDEX IF NOT EXISTS idx_invoice_client ON invoice (client_id);

-- 发票附件（扫描件）
CREATE TABLE IF NOT EXISTS invoice_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT       NOT NULL,
    -- scan=发票扫描件
    attachment_type VARCHAR(20)  NOT NULL DEFAULT 'scan',
    file_name       VARCHAR(255) NOT NULL,
    stored_name     VARCHAR(300) NOT NULL,
    file_size       BIGINT,
    content_type    VARCHAR(100),
    create_by       VARCHAR(50),
    create_time     TIMESTAMP,
    update_by       VARCHAR(50),
    update_time     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoice_attachment_inv ON invoice_attachment (invoice_id);

-- 收款挂到发票（历史收款 invoice_id 为空，仍按合同归属）
ALTER TABLE contract_payment ADD COLUMN invoice_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_payment_invoice ON contract_payment (invoice_id);

-- 发票管理菜单（业务管理目录 id=100，使用 180 段）
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(180, 100, '发票管理', '/business/invoice', 'business/invoice/index', 'business:invoice:list', 'Tickets', 1, 7, NOW());

INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(181, 180, '发票登记', NULL, NULL, 'business:invoice:add', NULL, 2, 1, NOW()),
(182, 180, '发票编辑', NULL, NULL, 'business:invoice:edit', NULL, 2, 2, NOW()),
(183, 180, '发票删除', NULL, NULL, 'business:invoice:delete', NULL, 2, 3, NOW()),
(184, 180, '发票状态流转', NULL, NULL, 'business:invoice:status', NULL, 2, 4, NOW());

-- 角色授权：系统管理员、项目经理全量
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT r.role_id, m.id FROM (VALUES (1), (2)) AS r(role_id)
CROSS JOIN sys_menu m WHERE m.id IN (180, 181, 182, 183, 184);

-- 角色授权：普通员工仅查询
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 180);

SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), (SELECT MAX(id) FROM sys_menu));
