-- V37: 业务类型字典（项目性质/项目类型/业务类型/字号/收费频度/税收分类/发票品名）
-- 数据来源：业务配置导出表，去重后共 84 行
CREATE TABLE IF NOT EXISTS business_type (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 项目性质：收入型 / 无收入型
    biz_nature    VARCHAR(20)  NOT NULL,
    -- 项目类型
    project_type  VARCHAR(50)  NOT NULL,
    -- 业务类型（同项目类型下唯一）
    biz_type      VARCHAR(100) NOT NULL,
    biz_desc      VARCHAR(500),
    -- 字号类型：审/验/咨/代/商（空表示不参与开票编号）
    no_char       VARCHAR(10),
    -- 收费频度：次/月度/季度
    fee_freq      VARCHAR(20),
    tax_code      VARCHAR(30),
    tax_class     VARCHAR(100),
    invoice_item  VARCHAR(100),
    sort          INT,
    create_by     VARCHAR(50),
    create_time   TIMESTAMP,
    update_by     VARCHAR(50),
    update_time   TIMESTAMP,
    CONSTRAINT uk_business_type UNIQUE (project_type, biz_type)
);

INSERT INTO business_type (biz_nature, project_type, biz_type, biz_desc, no_char, fee_freq, tax_code, tax_class, invoice_item, sort, create_by, create_time, update_by, update_time) VALUES
  ('收入型', '专项审计业务', '外汇审计', '出外汇审计报告', '审', '次', '3040602040000000000', '审计服务', '外汇审计费', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '商定程序业务', '商定程序业务', '出商定程序报告', '商', '次', '3040603990000000000', '其他咨询服务', '咨询费', 2, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '技术使用费/收入', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 3, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '内部运营', 'IT管理', '系统维护、网络安全、服务器管理、技术支持', NULL, NULL, NULL, NULL, NULL, 4, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '审阅', 'Q2', NULL, '审', '次', '3040602990000000000', '其他鉴证服务', '审阅费', 5, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '客户服务', '售后支持', '账务建议、答疑、数据追溯、后续指导', NULL, NULL, NULL, NULL, NULL, 6, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '审阅', 'Q4', NULL, '审', '次', '3040602990000000000', '其他鉴证服务', '审阅费', 7, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '涉税服务', '月度纳税申报', NULL, '咨', '月度', '3040802050000000000', '纳税申报代办', '代办费', 8, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '客户服务', '档案管理', '客户资料整理、合同管理、信息维护', NULL, NULL, NULL, NULL, NULL, 9, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '新设非首次出资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 10, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '技术开发', '工具开发', '审计软件、数据分析工具、自动化系统', NULL, NULL, NULL, NULL, NULL, 11, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '行业服务', '监管对接', '配合监管检查、政策征求意见、监管协调', NULL, NULL, NULL, NULL, NULL, 12, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '审阅', '日本财年年审', NULL, '审', '次', '3040602990000000000', '其他鉴证服务', '审阅费', 13, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '客户服务', '关系维护', '日常沟通、节日问候、满意度回访', NULL, NULL, NULL, NULL, NULL, 14, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '技术开发', '知识系统', '案例库、准则库、文档管理系统', NULL, NULL, NULL, NULL, NULL, 15, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '代表处清算', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 16, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '财产损失', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 17, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '内部运营', '行政后勤', '办公场所维护、资产管理、档案管理、文档管理', NULL, NULL, NULL, NULL, NULL, 18, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '行业服务', '学术交流', '高校合作、学术委员会研究、论文指导', NULL, NULL, NULL, NULL, NULL, 19, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财税咨询', '代理记账', NULL, '咨', '月度', '3040603060000000000', '会计咨询', '咨询费', 20, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO business_type (biz_nature, project_type, biz_type, biz_desc, no_char, fee_freq, tax_code, tax_class, invoice_item, sort, create_by, create_time, update_by, update_time) VALUES
  ('收入型', '财务报表审计', '年度审计', NULL, '审', '次', '3040602040000000000', '审计服务', '年度审计费', 21, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财税咨询', '月度咨询', NULL, '咨', '月度', '3040603060000000000', '会计咨询', '月度咨询费', 22, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '技术开发', '基础设施', '云服务器、数据备份、系统升级维护', NULL, NULL, NULL, NULL, NULL, 23, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '媒体公关', '新闻发布、公关维护、危机应对', NULL, NULL, NULL, NULL, NULL, 24, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '内部运营', '法务合规', '合同审核、知识产权保护、合规审查', NULL, NULL, NULL, NULL, NULL, 25, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', 'Q3', NULL, '审', '次', '3040602040000000000', '审计服务', '中期审计费', 26, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', '日本财年年审', NULL, '审', '次', '3040602040000000000', '审计服务', '日本财年年审费', 27, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', '年度审计（合并/部分）', NULL, '审', '次', '3040602040000000000', '审计服务', '年度审计费', 28, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '内部运营', '党建工作', '党组织建设、党员管理、党费收缴、党建活动组织、政治学习', NULL, NULL, NULL, NULL, NULL, 29, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '代表处年审', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 30, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '内部运营', '内部财务', '内部核算、预算编制、成本核算、固定资产管理', NULL, NULL, NULL, NULL, NULL, 31, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '业务对接', '中介合作、资源共享、业务联络', NULL, NULL, NULL, NULL, NULL, 32, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '客户服务', '知识分享', '政策解读讲座、专题分享、客户培训', NULL, NULL, NULL, NULL, NULL, 33, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '审阅', '特别期间', NULL, '审', '次', '3040602990000000000', '其他鉴证服务', '审阅费', 34, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '行业服务', '协会工作', '注协会议、行业活动、标准制定参与', NULL, NULL, NULL, NULL, NULL, 35, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '涉税服务', '企业所得税汇算清缴申报', NULL, '咨', '次', '3040802050000000000', '纳税申报代办', '代办费', 36, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '公益研讨会', '免费财务咨询、财税知识普及', NULL, NULL, NULL, NULL, NULL, 37, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '招投标准备', '标书制作、投标文件准备、资质整理', NULL, NULL, NULL, NULL, NULL, 38, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', 'Q1', NULL, '审', '次', '3040602040000000000', '审计服务', '中期审计费', 39, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财税咨询', '季度咨询', NULL, '咨', '季度', '3040603060000000000', '会计咨询', '季度咨询费', 40, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO business_type (biz_nature, project_type, biz_type, biz_desc, no_char, fee_freq, tax_code, tax_class, invoice_item, sort, create_by, create_time, update_by, update_time) VALUES
  ('收入型', '商务行政', '公司设立代办', NULL, '咨', '次', '3040802990000000000', '其他经纪代理服务', '代办费', 41, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '市场推广', '展会参与、论坛组织、业务拓展会议', NULL, NULL, NULL, NULL, NULL, 42, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '质量控制', '质量复核', '业务质量检查、底稿审核、项目监控', NULL, NULL, NULL, NULL, NULL, 43, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财税咨询', '研讨会', NULL, '咨', '次', '3040603060000000000', '会计咨询', '研讨会', 44, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '涉税服务', '个人所得税汇算清缴申报', NULL, '咨', '次', '3040802050000000000', '纳税申报代办', '代办费', 45, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '质量控制', '监管检查', '应对监管检查、自查自纠、整改', NULL, NULL, NULL, NULL, NULL, 46, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '质量控制', '职业道德', '独立性审查、利益冲突评估', NULL, NULL, NULL, NULL, NULL, 47, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '其他咨询', '资料翻译', NULL, '咨', '次', '3040603990000000000', '其他咨询服务', '翻译费', 48, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '质量控制', '风险管理', '客户风险评估、业务承接审批、职业保险', NULL, NULL, NULL, NULL, NULL, 49, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '公司清算二期', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 50, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '汇算清缴鉴证', NULL, '审', '次', '3040602020000000000', '涉税鉴证', '专项审计费', 51, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '涉税服务', '个人所得税月度申报', NULL, '咨', '月度', '3040802050000000000', '纳税申报代办', '代办费', 52, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '内容运营', '公众号维护、官网运营、文章撰写', NULL, NULL, NULL, NULL, NULL, 53, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '增资非首次出资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 54, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '其他咨询', '同期资料制作', NULL, '咨', '次', '3040603990000000000', '其他咨询服务', '同期资料制作费', 55, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '高新技术认定', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 56, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', '特别期间', NULL, '审', '次', '3040602040000000000', '审计服务', '中期审计费', 57, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', 'Q4', NULL, '审', '次', '3040602040000000000', '审计服务', '中期审计费', 58, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '审阅', 'Q1', NULL, '审', '次', '3040602990000000000', '其他鉴证服务', '审阅费', 59, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '财务报表特定要素审计', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 60, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO business_type (biz_nature, project_type, biz_type, biz_desc, no_char, fee_freq, tax_code, tax_class, invoice_item, sort, create_by, create_time, update_by, update_time) VALUES
  ('无收入型', '质量控制', '培训学习', '员工内部培训、案例研讨、继续教育、知识竞赛', NULL, NULL, NULL, NULL, NULL, 61, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '吸收合并', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 62, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '技术开发', '流程优化', '业务流程自动化、标准化、模板设计', NULL, NULL, NULL, NULL, NULL, 63, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '质量控制', '法规研究', '会计准则研究、政策研究、白皮书编写', NULL, NULL, NULL, NULL, NULL, 64, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '内部运营', '人力资源管理', '员工招聘、绩效考核、薪酬福利、员工关系', NULL, NULL, NULL, NULL, NULL, 65, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', 'Q2', NULL, '审', '次', '3040602040000000000', '审计服务', '中期审计费', 66, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '客户服务', '前期咨询', '投标前了解、项目可行性评估、需求沟通', NULL, NULL, NULL, NULL, NULL, 67, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', 'Instruction', 'Instruction', NULL, '咨', '次', '3040603990000000000', '其他咨询服务', '日本审计应对', 68, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '商务行政', '就业证代办', NULL, '咨', '次', '3040802990000000000', '其他经纪代理服务', '代办费', 69, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '新设首次出资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 70, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '增资首次出资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 71, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '利润分配', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 72, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财税咨询', '联结决算', NULL, '咨', '次', '3040603060000000000', '会计咨询', '联结决算', 73, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '商务行政', '行政变更代办', NULL, '咨', '次', '3040802990000000000', '其他经纪代理服务', '代办费', 74, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('无收入型', '业务拓展', '品牌建设', '事务所品牌形象、宣传物料设计', NULL, NULL, NULL, NULL, NULL, 75, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '减资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 76, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '新准则期初数', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 77, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '专项审计业务', '研发费加计扣除', NULL, '审', '次', '3040602040000000000', '审计服务', '专项审计费', 78, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '其他咨询', '特别调查(DD)', NULL, '咨', '次', '3040603990000000000', '其他咨询服务', '特别调查费', 79, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '利润增资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 80, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO business_type (biz_nature, project_type, biz_type, biz_desc, no_char, fee_freq, tax_code, tax_class, invoice_item, sort, create_by, create_time, update_by, update_time) VALUES
  ('收入型', '商务行政', '并购咨询', NULL, '咨', '次', '3040603990000000000', '其他咨询服务', '咨询费', 81, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '验资业务', '外债转增资', NULL, '验', '次', '3040602040000000000', '审计服务', '验资费', 82, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '审阅', 'Q3', NULL, '审', '次', '3040602990000000000', '其他鉴证服务', '审阅费', 83, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('收入型', '财务报表审计', '公司清算一期', NULL, '审', '次', '3040602040000000000', '审计服务', '中期审计费', 84, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- 项目表新增项目性质/业务类型，历史类型值归并到字典口径
ALTER TABLE project ADD COLUMN biz_nature VARCHAR(20);
ALTER TABLE project ADD COLUMN biz_type VARCHAR(100);
UPDATE project SET type = '财务报表审计' WHERE type IN ('审计', 'Audit', 'audit');
UPDATE project SET type = '验资业务' WHERE type = '验资';
UPDATE project SET type = '涉税服务' WHERE type IN ('税务', '税务咨询', '咨询');
UPDATE project SET type = '财税咨询' WHERE type = '代理记账';
UPDATE project SET biz_nature = '收入型' WHERE type IN ('财务报表审计', '验资业务', '涉税服务', '财税咨询', '专项审计业务', '审阅', '商定程序业务', '商务行政', '其他咨询', 'Instruction');

-- 合同表新增业务类型（字号按其字号类型解析）
ALTER TABLE contract ADD COLUMN biz_type VARCHAR(100);

-- 发票表新增开票要素（按业务类型自动带出）
ALTER TABLE invoice ADD COLUMN invoice_item VARCHAR(100);
ALTER TABLE invoice ADD COLUMN tax_code VARCHAR(30);
ALTER TABLE invoice ADD COLUMN tax_class VARCHAR(100);
