-- =====================================================
-- V3: 合同管理表结构（PostgreSQL）
-- =====================================================

CREATE TABLE IF NOT EXISTS contract (
    -- 主键
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 合同编号，规则 HT+yyyyMMdd+4位流水，全局唯一
    contract_no   VARCHAR(30)    NOT NULL,
    -- 合同名称
    name          VARCHAR(200)   NOT NULL,
    -- 客户名称（本期为文本字段）
    client_name   VARCHAR(200)   NOT NULL,
    -- 合同类型：审计/税务咨询/代理记账/评估等
    contract_type VARCHAR(50)    NOT NULL,
    -- 合同金额（元，两位小数）
    amount        NUMERIC(14, 2) NOT NULL,
    -- 签约日期
    sign_date     DATE           NOT NULL,
    -- 服务期限起
    service_start DATE           NOT NULL,
    -- 服务期限止
    service_end   DATE           NOT NULL,
    -- 项目负责人
    owner_name    VARCHAR(50)    NOT NULL,
    -- 状态：0-草稿 1-执行中 2-已完成 3-已终止
    status        SMALLINT       NOT NULL DEFAULT 0,
    -- 备注
    remark        VARCHAR(500),
    create_by     VARCHAR(50),
    create_time   TIMESTAMP,
    update_by     VARCHAR(50),
    update_time   TIMESTAMP,
    CONSTRAINT uk_contract_no UNIQUE (contract_no)
);

CREATE INDEX IF NOT EXISTS idx_contract_client_name ON contract (client_name);
CREATE INDEX IF NOT EXISTS idx_contract_status ON contract (status);
