-- V40: 站内通知 + 审计日志落库 + 系统管理新菜单

-- 站内通知（定时提醒生成，按 天+类型+关联对象 去重）
CREATE TABLE IF NOT EXISTS sys_notification (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    -- receivable=逾期应收 confirmation=函证逾期 reimbursement=报销滞留 contract=合同到期
    type          VARCHAR(30)  NOT NULL,
    title         VARCHAR(200) NOT NULL,
    content       VARCHAR(500),
    -- 点击跳转路由
    related_path  VARCHAR(200),
    related_id    BIGINT       NOT NULL DEFAULT 0,
    is_read       SMALLINT     NOT NULL DEFAULT 0,
    -- 去重日期（同一天同对象不重复生成）
    dedup_date    DATE         NOT NULL,
    create_time   TIMESTAMP,
    CONSTRAINT uk_notification_dedup UNIQUE (user_id, type, related_id, dedup_date)
);

CREATE INDEX IF NOT EXISTS idx_notification_user ON sys_notification (user_id, is_read);

-- 审计日志（@AuditLog 切面落库）
CREATE TABLE IF NOT EXISTS sys_audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50),
    operation     VARCHAR(100) NOT NULL,
    -- 成功 / 失败
    result        VARCHAR(20)  NOT NULL,
    error_msg     VARCHAR(300),
    cost_ms       BIGINT,
    ip            VARCHAR(50),
    create_time   TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_username ON sys_audit_log (username);
CREATE INDEX IF NOT EXISTS idx_audit_log_time ON sys_audit_log (create_time);

-- 系统管理菜单：业务类型字典（190 段）
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(190, 1, '业务类型字典', '/system/dict', 'system/dict/index', 'system:dict:list', 'Notebook', 1, 5, NOW());

INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(191, 190, '字典新增', NULL, NULL, 'system:dict:add', NULL, 2, 1, NOW()),
(192, 190, '字典编辑', NULL, NULL, 'system:dict:edit', NULL, 2, 2, NOW()),
(193, 190, '字典删除', NULL, NULL, 'system:dict:delete', NULL, 2, 3, NOW());

-- 系统管理菜单：审计日志（只读）
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(195, 1, '审计日志', '/system/audit', 'system/audit/index', 'system:audit:list', 'Document', 1, 6, NOW());

-- 角色授权：仅系统管理员
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT 1, m.id FROM sys_menu m WHERE m.id IN (190, 191, 192, 193, 195);

SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), (SELECT MAX(id) FROM sys_menu));
