-- =====================================================
-- V49: 客户联系人表
-- 客户详情拆分为 基本信息/开票信息/联系人，联系人可无限添加
-- =====================================================

CREATE TABLE IF NOT EXISTS client_contact (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT       NOT NULL,
    contact_name VARCHAR(100) NOT NULL,
    position     VARCHAR(100),
    phone        VARCHAR(50),
    email        VARCHAR(100),
    remark       VARCHAR(200),
    create_by    VARCHAR(50),
    create_time  TIMESTAMP,
    update_by    VARCHAR(50),
    update_time  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_client_contact_client ON client_contact (client_id);
