-- =====================================================
-- V54: 报销费用类别字典化
-- 费用类别（原前端硬编码）改为系统管理员可增删改的字典表
-- =====================================================

CREATE TABLE IF NOT EXISTS expense_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(30) NOT NULL,
    sort        INT         NOT NULL DEFAULT 0,
    -- 1-启用 0-停用（停用后新增报销不可再选，历史单据不受影响）
    status      SMALLINT    NOT NULL DEFAULT 1,
    create_time TIMESTAMP,
    CONSTRAINT uk_expense_category_name UNIQUE (name)
);

INSERT INTO expense_category (name, sort, status, create_time) VALUES
('差旅费', 1, 1, NOW()),
('交通费', 2, 1, NOW()),
('办公费', 3, 1, NOW()),
('餐饮费', 4, 1, NOW()),
('其他',   5, 1, NOW());

-- 类别设置权限按钮（仅授权系统管理员）
INSERT INTO sys_menu (id, parent_id, name, path, component, perm, icon, type, sort, create_time) VALUES
(126, 120, '报销类别设置', NULL, NULL, 'business:reimbursement:category', NULL, 2, 6, NOW());

INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 126);

SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), (SELECT MAX(id) FROM sys_menu));
