-- =====================================================
-- V5: 收款记录表结构（PostgreSQL）
-- =====================================================

CREATE TABLE IF NOT EXISTS contract_payment (
    -- 主键
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 关联合同 ID（应用层校验存在性与状态，不建物理外键）
    contract_id    BIGINT         NOT NULL,
    -- 收款金额（元），必须大于 0
    amount         NUMERIC(14, 2) NOT NULL,
    -- 收款日期
    payment_date   DATE           NOT NULL,
    -- 收款方式：转账/现金/支票/其他
    payment_method VARCHAR(30)    NOT NULL,
    -- 付款方
    payer_name     VARCHAR(100),
    -- 备注
    remark         VARCHAR(500),
    create_by      VARCHAR(50),
    create_time    TIMESTAMP,
    update_by      VARCHAR(50),
    update_time    TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payment_contract_id ON contract_payment (contract_id);
CREATE INDEX IF NOT EXISTS idx_payment_date ON contract_payment (payment_date);
