-- =====================================================
-- V60: 合同收款计划节点
-- 合同可登记分期收款计划(日期+金额),到期未收生成提醒;
-- 合同汇总增加 计划合计 与 计划vs实际 对比
-- =====================================================

CREATE TABLE IF NOT EXISTS contract_payment_plan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT       NOT NULL,
    due_date    DATE         NOT NULL,
    amount      NUMERIC(18,2) NOT NULL,
    remark      VARCHAR(200),
    create_by   VARCHAR(50),
    create_time TIMESTAMP,
    CONSTRAINT uk_plan_contract UNIQUE (contract_id, due_date, amount)
);

CREATE INDEX IF NOT EXISTS idx_plan_contract ON contract_payment_plan (contract_id);
CREATE INDEX IF NOT EXISTS idx_plan_due_date ON contract_payment_plan (due_date);
