-- V76: 供应商主数据
-- 对公付款的供应商此前是自由文本，同一供应商多种写法导致按供应商统计失真。
-- 建主数据表并从既有付款单回填，付款登记时下拉选择（仍允许临时输入）。
CREATE TABLE IF NOT EXISTS vendor (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_name  VARCHAR(200) NOT NULL,
    tax_no       VARCHAR(60),
    bank_account VARCHAR(80),
    contact      VARCHAR(60),
    phone        VARCHAR(40),
    remark       VARCHAR(200),
    create_by    VARCHAR(50),
    create_time  TIMESTAMP NOT NULL DEFAULT NOW(),
    update_time  TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_vendor_name ON vendor (vendor_name);

-- 从既有付款单回填供应商
INSERT INTO vendor (vendor_name, create_by)
SELECT DISTINCT vp.vendor_name, 'system'
FROM vendor_payment vp
WHERE vp.vendor_name IS NOT NULL AND vp.vendor_name <> ''
  AND NOT EXISTS (SELECT 1 FROM vendor v WHERE v.vendor_name = vp.vendor_name);
