-- =====================================================
-- V7: 报销单表结构（PostgreSQL）
-- =====================================================

CREATE TABLE IF NOT EXISTS reimbursement (
    -- 主键
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 报销编号，规则 BX+yyyyMMdd+4位流水，全局唯一
    reimbursement_no    VARCHAR(30)    NOT NULL,
    -- 申请人账号
    applicant_username  VARCHAR(50)    NOT NULL,
    -- 申请人姓名
    applicant_name      VARCHAR(50),
    -- 关联合同 ID（可空，用于项目成本归集）
    contract_id         BIGINT,
    -- 费用类别：差旅费/交通费/办公费/餐饮费/其他
    category            VARCHAR(30)    NOT NULL,
    -- 报销金额（元）
    amount              NUMERIC(14, 2) NOT NULL,
    -- 费用发生日期
    expense_date        DATE           NOT NULL,
    -- 事由说明
    title               VARCHAR(200)   NOT NULL,
    -- 状态：0-待审批 1-已批准 2-已驳回
    status              SMALLINT       NOT NULL DEFAULT 0,
    -- 审批人账号
    approver_username   VARCHAR(50),
    -- 审批人姓名
    approver_name       VARCHAR(50),
    -- 审批时间
    approve_time        TIMESTAMP,
    -- 审批意见
    approve_comment     VARCHAR(300),
    create_by           VARCHAR(50),
    create_time         TIMESTAMP,
    update_by           VARCHAR(50),
    update_time         TIMESTAMP,
    CONSTRAINT uk_reimbursement_no UNIQUE (reimbursement_no)
);

CREATE INDEX IF NOT EXISTS idx_reimbursement_applicant ON reimbursement (applicant_username);
CREATE INDEX IF NOT EXISTS idx_reimbursement_status ON reimbursement (status);
CREATE INDEX IF NOT EXISTS idx_reimbursement_contract_id ON reimbursement (contract_id);
