-- =====================================================
-- V9: 函证表结构（PostgreSQL）
-- =====================================================

CREATE TABLE IF NOT EXISTS confirmation (
    -- 主键
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 函证编号，规则 HZ+yyyyMMdd+4位流水，全局唯一
    confirmation_no  VARCHAR(30)  NOT NULL,
    -- 函证类型：银行函证/往来款函证/其他
    type             VARCHAR(30)  NOT NULL,
    -- 被函证单位
    target_unit      VARCHAR(200) NOT NULL,
    -- 函证内容摘要
    summary          VARCHAR(500) NOT NULL,
    -- 关联合同 ID（可空）
    contract_id      BIGINT,
    -- 状态：0-未发出 1-已发出 2-已回函 3-已作废
    status           SMALLINT     NOT NULL DEFAULT 0,
    -- 发出日期
    sent_date        DATE,
    -- 回函日期
    confirmed_date   DATE,
    create_by        VARCHAR(50),
    create_time      TIMESTAMP,
    update_by        VARCHAR(50),
    update_time      TIMESTAMP,
    CONSTRAINT uk_confirmation_no UNIQUE (confirmation_no)
);

CREATE INDEX IF NOT EXISTS idx_confirmation_status ON confirmation (status);
CREATE INDEX IF NOT EXISTS idx_confirmation_contract_id ON confirmation (contract_id);
